version: '3.1'

services:

  db:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: Muny0l3cl41r3
      MYSQL_DATABASE: clairepay
    ports:
      - 3306:3306